In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\Sushant\Desktop\Datasets\heart_disease dataset.csv")
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [4]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [5]:
data["target"].value_counts()

1    526
0    499
Name: target, dtype: int64

In [6]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [7]:
from imblearn.over_sampling import RandomOverSampler
ro=RandomOverSampler()
x_data,y_data=ro.fit_resample(x,y)

In [8]:
from collections import Counter
print("Actual data",Counter(y))
print("Artificial",Counter(y_data))

Actual data Counter({1: 526, 0: 499})
Artificial Counter({0: 526, 1: 526})

In [9]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=2,random_state=0,shuffle=True)
kf.get_n_splits(x_data)
print(kf)

KFold(n_splits=2, random_state=0, shuffle=True)

In [10]:
for train_index,test_index in kf.split(x_data):
    print("TRAIN:",train_index,"TEST:",test_index)
    x_train,x_test=x_data[train_index],x_data[test_index]
    y_train,y_test=y_data[train_index],y_data[test_index]

TRAIN: [   0    3    4    7   11   13   16   19   22   23   24   25   26   28
   29   32   33   36   41   42   43   44   47   51   53   56   57   58
   59   61   63   67   69   72   73   74   80   82   83   84   86   87
   88   89   91   93   94   95   96   98   99  102  106  107  110  111
  112  114  115  117  119  120  121  123  126  128  129  130  131  132
  134  135  136  137  138  139  143  146  147  148  149  151  152  153
  160  163  164  166  168  169  173  174  176  180  182  183  184  185
  189  191  195  197  199  201  203  205  207  209  212  213  216  217
  218  219  221  223  225  226  227  228  232  234  237  244  246  248
  254  256  257  259  260  265  269  273  274  275  276  277  280  281
  282  284  286  287  288  289  290  291  292  296  297  300  305  307
  314  321  322  323  324  326  327  328  329  335  336  339  340  341
  343  347  348  349  353  354  355  357  360  365  368  369  370  371
  373  374  375  376  377  381  383  387  388  392  393  394  398  400
  401  404  405  407  410  411  414  417  419  421  423  426  428  429
  430  433  437  438  441  442  444  445  446  448  449  450  454  455
  459  460  461  463  464  468  469  470  473  475  476  480  488  490
  497  498  499  502  504  507  508  509  510  512  514  515  516  517
  519  525  528  532  534  536  537  539  540  541  542  543  544  547
  550  551  552  554  555  556  558  559  560  562  563  565  566  568
  570  572  573  574  575  577  579  581  582  584  586  589  591  593
  594  595  598  599  600  602  603  604  606  607  609  610  611  612
  616  617  621  623  628  631  632  633  636  637  639  645  647  649
  653  657  659  660  662  663  668  669  672  673  675  677  681  684
  685  687  690  694  696  697  699  700  701  702  705  708  709  710
  713  714  716  718  719  722  723  726  727  729  730  732  734  735
  738  739  747  749  750  754  755  756  758  761  763  765  766  767
  768  770  771  774  776  777  778  779  782  785  791  792  793  794
  797  800  802  804  806  809  810  811  812  813  814  815  816  818
  820  825  829  830  833  835  837  840  841  843  845  846  847  849
  850  853  854  856  860  861  862  866  868  870  872  875  878  879
  881  882  883  886  887  888  889  891  894  896  897  898  899  900
  901  902  904  905  906  908  909  910  912  913  917  925  929  930
  932  933  936  937  938  939  941  942  943  944  950  952  953  954
  955  957  958  961  962  963  964  969  972  974  976  978  979  982
  985  994  997  999 1000 1002 1003 1004 1005 1009 1010 1012 1015 1016
 1018 1020 1023 1024 1026 1027 1030 1031 1033 1034 1035 1036 1037 1039
 1040 1041 1042 1043 1045 1047 1048 1051] TEST: [   1    2    5    6    8    9   10   12   14   15   17   18   20   21
   27   30   31   34   35   37   38   39   40   45   46   48   49   50
   52   54   55   60   62   64   65   66   68   70   71   75   76   77
   78   79   81   85   90   92   97  100  101  103  104  105  108  109
  113  116  118  122  124  125  127  133  140  141  142  144  145  150
  154  155  156  157  158  159  161  162  165  167  170  171  172  175
  177  178  179  181  186  187  188  190  192  193  194  196  198  200
  202  204  206  208  210  211  214  215  220  222  224  229  230  231
  233  235  236  238  239  240  241  242  243  245  247  249  250  251
  252  253  255  258  261  262  263  264  266  267  268  270  271  272
  278  279  283  285  293  294  295  298  299  301  302  303  304  306
  308  309  310  311  312  313  315  316  317  318  319  320  325  330
  331  332  333  334  337  338  342  344  345  346  350  351  352  356
  358  359  361  362  363  364  366  367  372  378  379  380  382  384
  385  386  389  390  391  395  396  397  399  402  403  406  408  409
  412  413  415  416  418  420  422  424  425  427  431  432  434  435
  436  439  440  443  447  451  452  453  456  457  458  462  465  466
  467  471  472  474  477  478  479  481  482  483  484  485  486  487
  489  491  492  493  494  495  496  500  501  503  505  506  511  513
  518  520  521  522  523  524  526  527  529  530  531  533  535  538
  545  546  548  549  553  557  561  564  567  569  571  576  578  580
  583  585  587  588  590  592  596  597  601  605  608  613  614  615
  618  619  620  622  624  625  626  627  629  630  634  635  638  640
  641  642  643  644  646  648  650  651  652  654  655  656  658  661
  664  665  666  667  670  671  674  676  678  679  680  682  683  686
  688  689  691  692  693  695  698  703  704  706  707  711  712  715
  717  720  721  724  725  728  731  733  736  737  740  741  742  743
  744  745  746  748  751  752  753  757  759  760  762  764  769  772
  773  775  780  781  783  784  786  787  788  789  790  795  796  798
  799  801  803  805  807  808  817  819  821  822  823  824  826  827
  828  831  832  834  836  838  839  842  844  848  851  852  855  857
  858  859  863  864  865  867  869  871  873  874  876  877  880  884
  885  890  892  893  895  903  907  911  914  915  916  918  919  920
  921  922  923  924  926  927  928  931  934  935  940  945  946  947
  948  949  951  956  959  960  965  966  967  968  970  971  973  975
  977  980  981  983  984  986  987  988  989  990  991  992  993  995
  996  998 1001 1006 1007 1008 1011 1013 1014 1017 1019 1021 1022 1025
 1028 1029 1032 1038 1044 1046 1049 1050]
TRAIN: [   1    2    5    6    8    9   10   12   14   15   17   18   20   21
   27   30   31   34   35   37   38   39   40   45   46   48   49   50
   52   54   55   60   62   64   65   66   68   70   71   75   76   77
   78   79   81   85   90   92   97  100  101  103  104  105  108  109
  113  116  118  122  124  125  127  133  140  141  142  144  145  150
  154  155  156  157  158  159  161  162  165  167  170  171  172  175
  177  178  179  181  186  187  188  190  192  193  194  196  198  200
  202  204  206  208  210  211  214  215  220  222  224  229  230  231
  233  235  236  238  239  240  241  242  243  245  247  249  250  251
  252  253  255  258  261  262  263  264  266  267  268  270  271  272
  278  279  283  285  293  294  295  298  299  301  302  303  304  306
  308  309  310  311  312  313  315  316  317  318  319  320  325  330
  331  332  333  334  337  338  342  344  345  346  350  351  352  356
  358  359  361  362  363  364  366  367  372  378  379  380  382  384
  385  386  389  390  391  395  396  397  399  402  403  406  408  409
  412  413  415  416  418  420  422  424  425  427  431  432  434  435
  436  439  440  443  447  451  452  453  456  457  458  462  465  466
  467  471  472  474  477  478  479  481  482  483  484  485  486  487
  489  491  492  493  494  495  496  500  501  503  505  506  511  513
  518  520  521  522  523  524  526  527  529  530  531  533  535  538
  545  546  548  549  553  557  561  564  567  569  571  576  578  580
  583  585  587  588  590  592  596  597  601  605  608  613  614  615
  618  619  620  622  624  625  626  627  629  630  634  635  638  640
  641  642  643  644  646  648  650  651  652  654  655  656  658  661
  664  665  666  667  670  671  674  676  678  679  680  682  683  686
  688  689  691  692  693  695  698  703  704  706  707  711  712  715
  717  720  721  724  725  728  731  733  736  737  740  741  742  743
  744  745  746  748  751  752  753  757  759  760  762  764  769  772
  773  775  780  781  783  784  786  787  788  789  790  795  796  798
  799  801  803  805  807  808  817  819  821  822  823  824  826  827
  828  831  832  834  836  838  839  842  844  848  851  852  855  857
  858  859  863  864  865  867  869  871  873  874  876  877  880  884
  885  890  892  893  895  903  907  911  914  915  916  918  919  920
  921  922  923  924  926  927  928  931  934  935  940  945  946  947
  948  949  951  956  959  960  965  966  967  968  970  971  973  975
  977  980  981  983  984  986  987  988  989  990  991  992  993  995
  996  998 1001 1006 1007 1008 1011 1013 1014 1017 1019 1021 1022 1025
 1028 1029 1032 1038 1044 1046 1049 1050] TEST: [   0    3    4    7   11   13   16   19   22   23   24   25   26   28
   29   32   33   36   41   42   43   44   47   51   53   56   57   58
   59   61   63   67   69   72   73   74   80   82   83   84   86   87
   88   89   91   93   94   95   96   98   99  102  106  107  110  111
  112  114  115  117  119  120  121  123  126  128  129  130  131  132
  134  135  136  137  138  139  143  146  147  148  149  151  152  153
  160  163  164  166  168  169  173  174  176  180  182  183  184  185
  189  191  195  197  199  201  203  205  207  209  212  213  216  217
  218  219  221  223  225  226  227  228  232  234  237  244  246  248
  254  256  257  259  260  265  269  273  274  275  276  277  280  281
  282  284  286  287  288  289  290  291  292  296  297  300  305  307
  314  321  322  323  324  326  327  328  329  335  336  339  340  341
  343  347  348  349  353  354  355  357  360  365  368  369  370  371
  373  374  375  376  377  381  383  387  388  392  393  394  398  400
  401  404  405  407  410  411  414  417  419  421  423  426  428  429
  430  433  437  438  441  442  444  445  446  448  449  450  454  455
  459  460  461  463  464  468  469  470  473  475  476  480  488  490
  497  498  499  502  504  507  508  509  510  512  514  515  516  517
  519  525  528  532  534  536  537  539  540  541  542  543  544  547
  550  551  552  554  555  556  558  559  560  562  563  565  566  568
  570  572  573  574  575  577  579  581  582  584  586  589  591  593
  594  595  598  599  600  602  603  604  606  607  609  610  611  612
  616  617  621  623  628  631  632  633  636  637  639  645  647  649
  653  657  659  660  662  663  668  669  672  673  675  677  681  684
  685  687  690  694  696  697  699  700  701  702  705  708  709  710
  713  714  716  718  719  722  723  726  727  729  730  732  734  735
  738  739  747  749  750  754  755  756  758  761  763  765  766  767
  768  770  771  774  776  777  778  779  782  785  791  792  793  794
  797  800  802  804  806  809  810  811  812  813  814  815  816  818
  820  825  829  830  833  835  837  840  841  843  845  846  847  849
  850  853  854  856  860  861  862  866  868  870  872  875  878  879
  881  882  883  886  887  888  889  891  894  896  897  898  899  900
  901  902  904  905  906  908  909  910  912  913  917  925  929  930
  932  933  936  937  938  939  941  942  943  944  950  952  953  954
  955  957  958  961  962  963  964  969  972  974  976  978  979  982
  985  994  997  999 1000 1002 1003 1004 1005 1009 1010 1012 1015 1016
 1018 1020 1023 1024 1026 1027 1030 1031 1033 1034 1035 1036 1037 1039
 1040 1041 1042 1043 1045 1047 1048 1051]

In [11]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

from sklearn.model_selection import cross_val_score
scores=cross_val_score(classifier,x_train,y_train,cv=kf)
print(scores)
print(np.mean(scores)*100)

[0.80228137 0.8365019 ]
81.93916349809886

In [12]:
from sklearn.model_selection import cross_val_predict
y_pred=cross_val_predict(classifier,x_test,y_test,cv=kf)
y_pred

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)